//// Users
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL'

export const FORGOT_PASSWORD_EMAIL_REQUEST = 'FORGOT_PASSWORD_EMAIL_REQUEST'
export const FORGOT_PASSWORD_EMAIL = 'FORGOT_PASSWORD_EMAIL'
export const FORGOT_PASSWORD_EMAIL_FAIL = 'FORGOT_PASSWORD_EMAIL_FAIL'
export const FORGOT_PASSWORD_EMAIL_RESET = 'FORGOT_PASSWORD_EMAIL_RESET'

export const RESET_PASSWORD_EMAIL_REQUEST = 'RESET_PASSWORD_EMAIL_REQUEST'
export const RESET_PASSWORD_EMAIL = 'RESET_PASSWORD_EMAIL'
export const RESET_PASSWORD_EMAIL_FAIL = 'RESET_PASSWORD_EMAIL_FAIL'
export const RESET_PASSWORD_EMAIL_RESET = 'RESET_PASSWORD_EMAIL_RESET'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER = 'LOAD_USER'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const MY_PROFILE_REQUEST = 'MY_PROFILE_REQUEST'
export const MY_PROFILE = 'MY_PROFILE'
export const MY_PROFILE_FAIL = 'MY_PROFILE_FAIL'

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'

export const DELETE_PROFILE_REQUEST = 'DELETE_PROFILE_REQUEST'
export const DELETE_PROFILE = 'DELETE_PROFILE'
export const DELETE_PROFILE_FAIL = 'DELETE_PROFILE_FAIL'


//// POST


export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'
export const CREATE_POST_RESET = "CREATE_POST_RESET"

export const UPDATE_POST_RESET = 'UPDATE_POST_RESET'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'

export const DELETE_POST_RESET = 'DELETE_POST_RESET'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const GET_POST_OF_FOLLOWING_REQUEST = 'GETPOSTOFFOLLOWING_REQUEST'
export const GET_POST_OF_FOLLOWING_SUCCESS = 'GETPOSTOFFOLLOWING_SUCCESS'
export const GET_POST_OF_FOLLOWING_FAIL = 'GETPOSTOFFOLLOWING_FAIL'

export const LIKE_AND_UNLIKE_POST_REQUEST = 'LIKE_AND_UNLIKE_POST_REQUEST'
export const LIKE_AND_UNLIKE_POST_SUCCESS = 'LIKE_AND_UNLIKE_POST_SUCCESS'
export const LIKE_AND_UNLIKE_POST_FAIL = 'LIKE_AND_UNLIKE_POST_FAIL'
export const LIKE_AND_UNLIKE_POST_RESET = "LIKE_AND_UNLIKE_POST_RESET"


export const COMMENT_ON_POST_REQUEST = 'COMMENTONPOST_REQUEST'
export const COMMENT_ON_POST_SUCCESS = 'COMMENTONPOST_SUCCESS'
export const COMMENT_ON_POST_FAIL = 'COMMENTONPOST_FAIL'

export const DELETE_COMMENT_POST_REQUEST = 'DELETECOMMENTPOST_REQUEST'
export const DELETE_COMMENT_POST_SUCCESS = 'DELETECOMMENTPOST_SUCCESS'
export const DELETE_COMMENT_POST_FAIL = 'DELETECOMMENTPOST_FAIL'

export const GET_MY_POST_REQUEST = ' GET_MY_POST_REQUEST'
export const GET_MY_POST_SUCCESS = ' GET_MY_POST_SUCCESS'
export const GET_MY_POST_FAIL = ' GET_MY_POST_FAIL'

export const GET_USERS_POST_REQUEST = 'GET_USERS_POST_REQUEST'
export const GET_USERS_POST_SUCCESS = 'GET_USERS_POST_SUCCESS'
export const GET_USERS_POST_FAIL = 'GET_USERS_POST_FAIL'

export const GET_USERS_PROFILE_REQUEST = 'GET_USERS_PROFILE_REQUEST'
export const GET_USERS_PROFILE_SUCCESS = 'GET_USERS_PROFILE_SUCCESS'
export const GET_USERS_PROFILE_FAIL = 'GET_USERS_PROFILE_FAIL'


export const GET_All_USERS_REQUEST = "GET_All_USERS_REQUEST"
export const GET_All_USERS_SUCCESS = "GET_All_USERS_SUCCESS"
export const GET_All_USERS_FAIL = "GET_All_USERS_FAIL"


export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST'
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL'